package com.vadeworks.kannadafacts;

import java.util.Random;

/**
 * Created by ${Ashwin_Chandlapur} on 11/24/2016.
 */
public class facts {
    String facts[]={"Kannada is the only Indian language for which a foreigner Ferdinand Kittel wrote a Dictionary.",
            "Kannada script is the queen of World scripts –  Shri Vinobha Bhave",
            "The only Indian author who got maximum awards for literature is Shri Kuvempu, a proud Kannadiga.",
            "Kannada is one of the Indian languages to feature in Wikipedia logo",
            "'Charition mime', an ancient Greek play In 2nd century had used Kannada phrases.",
            "Ragale Saahithya can be seen only in Kannada, which is of a rare and different kind of literature.",
            "Shakuntala Devi who origins from Bengaluru is known as Human Computer.",
            "C.R Rao, mathematician and statistician of Karnataka is known for Cramér–Rao bound, the Rao–Blackwell theorem.",
            "Gangadhar rao deshpande is known as Karnataka Simha.",
            "Karnataka Ratna is the highest civilian honour of the State of Karnataka. There have been a total of 9 recipients of this award.",
            "The Maharaja of Mysore laid the foundation stone for the St.Philomena Cathedral church on October 28, 1933.",
            "Thatt Anta Heli on DD chandana, has entered Limca Book of Records as the longest running quiz show on any Indian Television Channel.",
            "Master Manjunath of Malgudi days, has got six national awards as a child artist",
            "P.Lankesh, the kannada journalist quit his job as an assistant professor in English at Bangalore University before he started Lankesh Patrike.",
            "Lankesh Patrike started in 1980, has never published a single advertisement or generated any ad revenue till date.",
            "Ondu Muttina Kathe is said to be the first Indian film to be shot underwater which was directed by Shankar nag.",
            "The Maharajas of Mysore were wealthy, second only to the Nizams of Hyderabad.",
            "The first Governer of Karnataka was Jai Chamarajendra wadeyar, who was the 25th and last Maharaja of the princely state of Mysore.",
            "Hampi in Bellary district is a UN World Heritage Site and has the most famous set of archaeological remnants.",
    "HMT watch manufacturing Unit at Bangalore was started in 1961.",
    "HMT at Bangalore is the first manufacturer of Wrist watches in the country. HMT is also India’s first Automatic Day-Date watch , first Quartz watch , first Braille watch, first Ana-Digi watch manufacturer.",
    "The first batch of Hand Wound Wrist Watches was released by the Hon’ble Prime Minister Pandit Jawaharlal Nehru.",
    "Kittur Rani Chennamma, Queen of the princely state of Kittur was the first woman to lead an armed rebellion against British governance and kappa tax in 1824",
    "Sangolli Rayanna, army chief of kittur was the first to start Guerilla warfare in India.",
    "Karnataka Khadi Gramodyoga Samyukta Sangha (KKGSS) in Bengeri in Hubli, is the only unit in India that is authorized to manufacture and supply the Flag of India from 1957.",
    "Purandara Dasa is known as the “Father of Carnatic Music”. He systematized the entire system of teaching Carnatic music that is followed to this day.",
    "Sir M Visvesvaraya's birthday which is on 15th September is celebrated as Engineer’s Day in India.",
    "Bharat Ratna awardee, Sir M Visvesvaraya was the chief engineer for the Krishna Raja Sagara (KRS) Dam in Mysore.",
    "Sir M.Visvesvaraya designed and planned the entire area of Jayanagar in South Bangalore. Its one of the best-planned layouts in Asia.",
    "Sir M.Visvesvaraya served as Board of director of Tata Steel during 1927–1955.",
    "Sir M Visvesvaraya designed the flood protection system for Hyderabad, Khadakvasala (Pune) and Gwalior and a sea erosion protection system for Vishakapatnam.",
    "Government College of Engineering(Now UVCE) was setup by Sir M Visvesvaraya in Bengaluru is the 1st Engineering institute in karnataka and 5th oldest in India.",
    "Sir M Visvesvaraya started Mysore Soap Factory, the Parasitoide Laboratory, the Mysore Iron & Steel Works in Bhadravathi",
    "Sir M Visvesvaraya started the famous State Bank of Mysore and Mysore Chambers of Commerce.",
    "The term Akashvani(All India Radio) was coined by MV Gopalswamy of Mysore.",
    "The state of Mysore state was formed on November 1st  1956 after the States Reorganization Act. From 1973 the state is known as Karnataka.",
    "Karnataka hosts the maximum number of Jnanapith awardees. The state has won eight awards.",
    "Banglore is known as silicon valley of India.",
    "The major river systems of karnatake are the Krishna and its tributaries, the Kaveri and its tributaries",
    "Karnataka is ranked 4th in size of legislature members with 224+75 member",
    "Karnataka is ranked  6th in terms of GDP (Gross Domestic Product) in India.",
    "Karnataka shares border with 6 states making it diverse in culture.",
    "Karnataka holds 3rd highest literacy rate (80.1%) after Kerala and Maharashtra",
    "Mullayanagiri  is highest point in karnataka standing upto 6317 feet. ",
    "Karnataka is the only exporter of sandalwood in the country.",
    "The first power station in Asia was set up in Karnataka at Shivanasamudra in 1902 to produce hydroelectric power.",
    "ISRO head office in bangalore and also home to prestigious higher institutes of learning such as the Indian Institute of Science (IISc) and the Indian Institute of Management (IIM Bangalore)",
    "Infosys in Mysore has the world's largest corporate training centre in the city.",
    "Mangalore handles 75 per cent of India's coffee exports and the bulk of its cashew nuts.",
    "Karnataka has 5 national parks and 19 Wildlife sanctuaries.",
    "The First commander-in-chief for Indian Army K.M Cariappa was born in Kodagu district.",
    "Namma Metro, is India's second largest metro system in terms of both length and number of stations, after the Delhi Metro.",
    "Tipu Sultan is known as Tiger of Mysore for his bravery in wars.",
    "Hardekar Manjappa of Uttara Kannada district is known is Gandhi of Karnataka.",
    "When the Kannada  literature “Kavirajamarga” was written by Amogavarsha, English was a baby in the cradle and Hindi was not born at all.",
            "M Govinda Pai is the first To conferred Rashtrakavi.",
            "Raghavanka is known as Shatpadi Brahma- 6 line Verse",
            "Rakkasa Tangadi Battle ruined Glory of Vijayanagara Empire in 1565",
            "Lucia is the first Crowd funded Kannada Movie.",
            "Mysore Paints and Varnish Limirted is the sole supplier of Voter's ink in India.",
            "Viduraswath in Karnataka is known as Jalianwala Bagh of South",
            "Kuvempu received Jnanapeetha for Shri Ramayana Darshanam",
            "Dha. Raa. Bendhre received Jnanapeetha for Naaku thanthi ",
            "Shivaram Karanth received Jnanapeetha for Mookajjiya Kanasugalu",
            "Masti Venkatesh Iyengar received Jnanapeetha for Chikkaveera Raajendhra",
            "Vi. Kru. Gokak received Jnanapeetha for Bhaaratha Sindhhu Rashmi",
            "Girish Karnad received Jnanapeetha for his works in Kannada Literature",
            "U. R. Ananthamurthy received Jnanapeetha for his works in Kannada Literature",
            "Chandrashekar Kambar received Jnanapeetha for his contribution to the literature field.",
            "The Jnanapeetha award carries a cheque for Rs. 5,00,000.00 a citation plaque and a bronze replica of Vagdevi.",
            "Gol Gumbaz, situated in Bijapur is an astounding engineering feat.The dome is the second largest in the world, 124 feet in diameter.",
            "Halebidu was the capital of Hoysala Empire which was at those times known as Dwarasamudra.",
            "The Bull Temple situated in Bangalore , houses the 4.57 m high and 6.10 m long image of Nandi, Lord Shiva's bull. The temple was built by Kempe Gowda in the 16th century.",
            "The University of Mysore became the first University outside the domain of the English administration in India",
            "Kaveri river is also called as the Ganges of the south, its tributaries include Shimsa, Hemavati, Arkavathi, Kapila, Honnuhole, Lakshmana Tirtha, Kabini, Bhavani, Lokapavani, Noyyal and Amaravati rivers. ",
            "The Sharavathi is a river in India that originates at Ambuthirtha in Thirthahalli taluk, flows north-west through the Western Ghats forming the Jog Falls before joining the Arabian Sea at Honavara. ",
            "Yakshagana is one of the most living art traditions in the Karnataka.Yakshagana is a traditional theatre form combining dance, music, spoken word, costume-makeup, and stage technique with a distinct style and form. It is mainly prevalent in the coastal districts and malenadu areas of karnataka. Experts have placed the origin of Yakshagana at the 11th Century",
            "Karnataka witnesses about 12,000 Yakshagana performances every year.",
            "Nalvadi KrishnaRaja Wodeyar has been compared to the Emperor Ashoka by the English statesman Lord Samuel. Mahatma Gandhi called him Rajarshi.",
            "Manjarabad fort is a star fort built in 1792 by Tipu Sultan the then ruler of Mysore, it was  developed by the French architect Sebastien Le Prestre de Vauban.",
            "Two prominent and old areas of Bangalore were used to create Malgudi, the first few letters from Malleshwaram (Mal) and last few letters of Basavanagudi(gudi)",
            "The Old Mysore palace was destroyed in fire in 1897. The new Mysore Palace was built in 1912, at a cost of Rs.41.50 lakhs in the Indo-Saracenic style. Henry Irwin was the architect, and E.W. Fritchley worked as consulting Engineer.",
            "The Amba-Vilas Palace was built in 1912, at a cost of Rs.41.50 lakhs in the Indo-Saracenic style. Henry Irwin was the architect, and E.W. Fritchley worked as consulting Engineer.",
            "Avani is a temple in kolar, it is believed that Goddess Sita gave birth to Lava-Kusha in this place.",
            "The Early capital of Ganga Empire was Manyapura which is around near Nelamangala.",
            "Karnataka's State Tree - Sandalwood",
            "Karnataka State Flower - Lotus State",
            "Karnataka's State Animal - Asian Elephant",
            "Karnataka's State Bird - Indian Roller",
            "Karnataka's State Dance - Yakhsgan",
            "State Emblem - Gandaberunda (two headed mythological bird)",
            "The Rajyotsava Awards, are the second highest civilian honor of the Karnataka state. It is conferred annually on 1st November",
            "Lalbhag has around 673 genera and 1,854 species of plants.",
            "Mirjan Fort was built by Queen Chennabhairadevi of Gersoppa.",
            "When King Rugmagada Raya's younger daughter was given away in marriage, she brought with her a pretty portion of the Western Ghats as her dowry, thus giving the place its name - Chikka-magal-uru or Younger Daughter's Village.",
            "Sufi mystic Baba Budan smuggled seven coffee beans from Yemen into India, thus starting Coffee Plantation in India",
            "Baba Budangiri gets his name from Baba Budan who smuggled 7 Coffee beans from Yemen into India",
            "Sharavathi river tumbles as Jog Falls and it makes a spectacular drop of 253m in four distinct cascades - known locally as Raja, Rani, Rover and Rocket - to create the highest falls in Asia.",
            "Channapattana's traditional craft of wooden toys is protected as a geographical indication under the World Trade Organization.",
            "Kempe Gowda Circle in Bangalore was called Hanumanthapura. It was named after the chieftan Hanumantha Nayaka who built the Dharmabudhi lake",
            "Majestic and got its name because of the film theater of the same name which existed there till recently.",
            "During the days of the maharajs, the elephants march all the way to the palace for Dasara, the march is called Gajapayana ",
            "Sand Sculpture Museum at Mysore is India's First Sand Sculpture Museum.",
            "Sand Sculpture Museum at Mysore was done With 115 truckloads of sand and with more than 150 huge Sculptures.",
            "Sand Sculpture Museum at Mysore displays more than 16 themes describing the Heritage of Mysore.",
            "The wax museum at Mysore has 110 life size wax statues and more than 300 Indian and western musical instruments.",
            "The Khwaja Bande Nawaz Dargah library houses almost 10,000 books on various subjects in Urdu, Persian and Arab",
            "Moodabidri is known as the Jain Varanasi of South India.",
            "The Clock Tower in Mysore was erected during the Silver Jubilee of the reign of Maharaja Krishnaraja Wodeyar IV on 8th August 1927.",
            "Kudalasangama is at  the confluence of the rivers Krishna and Malaprabha",
            "The Vaidyanateshwara temple comes to life when it is excavated once every 12 years during the Panchalinga Darshana",
            "Every year, during Makara Sankranthi, Gangadhareshwara cave temple witnesses a strange phenomenon, a ray of light passes precisely between the horns of the stone bull outside the temple, and illuminates the deity inside the cave.",
            "Belur is known as \"Jewel In Stone\", a title it's held unsurpassed since 1116 AD",
            "Bylukuppe is the largest Tibetan settlements in South India.",
            "Bylukuppe is renowned as the seat of the Panchen Lama.",
            "The Royal family lived in Jagan Mohana Palace till the construction of the new Amba Vilas Mysore Palace",
            "The installation of Krishnaraja Wodeyar IV took place in 1902, attended by Lord Curzon, the then Viceroy and Governor-General of India.",
            "Anjanadri Hills near gangavathi taluk is believed to be the birthplace of Hanuman.",
            "Dodda Aalada Mara located near Bangalore is 400 year old Banyan tree.",
            "The annual electric output of Alamatti dam is 560 MU.",
            "Alamatti dam holds a gross water storage capacity of 123.08 TMC.",
            "Tungabhadra dam is the largest dam in Karnataka.",
            "Vani Vilasa Sagara Dam is also known as Mari Kanive located at Chitradurga, is the oldest dam in the Karnataka state.",
            "Akashvani was setup in Mysore on September 10,1935",
            "Savanadurga is the largest monolith hills in Asia",
            "Mangaluru Samachara is the first Kannada Newspaper",
            "Da Ra Bendre is known as Varakavi meaning Gifted Poet.",
            "Hubli-Dharwad are referred as Twin Cities.",
            "Master Kishan is the World's youngest film director at the age of 16.",
            "Hubli is known as Chota Mumbai",
            "Singapuradalli Rajakulla is the first kannada film shot abroad",
            "Chinnaswamy Stadium can seat 55,000 people.",
            "Javagal Srinath is known as Mysore Express",
            "Kannada's first female poet is Akkamahadevi",
            "Mullayanagiri is the highest peak in Karnataka",
            "Agumbe records second highest annual rainfall in India.",
            "Singanalluru Puttaswamayya Mutturaju is the birth name of Dr.Rajkumar.",
            "Subbaiyanaidu is the first Hero in Kannada Cinemas.",
            "Pampa is known as Adhikavi.",
            "The National Institute of Technology, Suratkal is the only college in India that has its own private beach, including a lighthouse.",
            "Bangalore is also the fashion capital of the East. It has as many fashion companies as Paris.",
            "Shankar Nag's Hosa Theerpu is his only directorial remake in his carrier.",
            "Except for the Gulf Region, Bangalore sends highest number of professionals abroad, especially to USA. ",
            "The Forbes magazine considers Bangalore as one of “The Next Decade’s Fastest-Growing Cities”.",
            "Bangalore is the base for nearly 47% of the 265 biotechnology companies in India. ",
            "Bangalored is a phrase used by Americans which refers to workers being laid off because their jobs have moved to Bangalore through IT Outsourcing.",
            "Winston Churchill owes Rs. 13 to the Bangalore Club",
            "40% of Bangalore's landscape is gardens/parks and 15% lakes/ponds.",
            "Mysore is the Cleanest city in India.",
            "Mysore is Famous for Mysore Silk, Mysore Masala Dosa, Mysore mallige, Mysore Pak Sweet, Mysore Beetle Leaves ",
            "Mysore zoo is 3rd best zoo in Asia",
            "Mysore is one of the four cities in india where currency notes are printed.",
            "Mysore's Karanji Lake's Aviary Is The Biggest 'Walk Through' Aviary In India.",
            "The Oriental Research library has a collection of around 50,000 palm leaf manuscripts",
            "Aihole is known as the cradle of Hindu rock architecture with over 125 temples and monuments.",
            "Hampi, in the Bellary District, has 54 World Heritage monuments and 650 national monuments.",
            "The earliest Stone Age fossil found in India is a hand axe at Lingasugur, in Raichur district.",
            "Iron weapons from 1200 BC, found at Hallur in Dharwad district, demonstrate that North Karnataka used iron earlier than northern India.",
            "Aihole has amazing monuments though it was an experimental base for architectural creation during the period of Chalukya.",
            "Scholars agree that the kings of the imperial Rashtrakuta dynasty from eighth to tenth century made the Kannada language as important as Sanskrit.",
            "Vijayanagara Empire is considered the greatest medieval Hindu empire and was one of the greatest in the world at that point of time.",
            "Harihara and Bukka are the founders of the Vijayanagara empire, who were commanders in the army of the Hoysala Empire.",
            "Dasara festival has been celebrated by the Wodeyars at Srirangapatna since 1610.",
            "CFTRI, one of the 40 national research laboratories in India was opened on 21 October 1950 in Mysore, Karnataka.",
            "The first railway line established in the city was the Bangalore–Mysore Junction metre gauge line, which was commissioned in 1882.",
            "The oldest available Kannada dictionary was composed by the poet 'Ranna' called 'Ranna Kanda' in 996 AD",
            "State Bank of Mysore was established in the year 1913 as The Bank of Mysore Ltd under the patronage of Maharaja Krishna Raja Wadiyar IV.",
            "State Bank of Mysore founded by Sir M Visvesvaraya, has a record of uninterrupted profits since 1913.",
            "The iconic stone chariot in Hampi is a symbol of Karnataka Tourism. A brick tower above it which was demolished during invasions.",
            "Basaveshwara is the first Kannadiga in whose honour a commemorative coin has been minted in recognition of his social reforms.",
            "The Prime Minister of India Narendra Modi inaugurated the statue of Basaveshwara , a kannada poet along the bank of the river Thames at Lambeth in London.",
            "The Mahamastakabhisheka festival is held once in 12 years, when the Gommateshwara statue is anointed with milk, saffron, ghee, etc. to maintain its freshness.",
            "On August 5, 2007, the statue at Shravanabelagola was voted by the readers of Times of India as the first of the Seven Wonders of India.",
            "Gommateshwara Statue at Shravanbelagola, a 57-foot (17 m) high monolithic statue is dedicated to the Jain god Bahubali.",
            "Gommateshwara Statue at Shravanbelagola, built in 983 A.D. is one of the largest free standing statues in the world.",
            "Apart Gommateshwara statue at Shravana Belgola, There are 4 other Gommateshwara statues in Karnataka.",
            "The Famous Chennakeshava Temple in Belur, was built on the banks of the Yagachi River in 1117 AD, by the Hoysala King Vishnuvardhana.",
            "Krishna Raja Sagara (KRS) Dam in Mandya was the first to install Automated Crest gates in India.",
            "Indian Institute of Science, Bangalore has India's first petascale supercomputer (CrayXC-40) and also the fastest supercomputer in India.",
            "KGF was known as \"Little England\" by the British, due to its more temperate weather and a landscape more similar to Britain's.",
            "C.N.R.Rao from Bangalore was the third scientist to receive the Bharata Ratna award after C.V. Raman and A. P. J. Abdul Kalam.",
            "Namma metro trains have a top speed of 80kmph and maintaince an average speed of 34kmph.",
            "Tipu Sultan is belived to be the innovator of the world's first war rocket. Two of the rockets in war, captured by the British at Srirangapatna, are displayed in the Royal Artillery Museum in London.",
            "There are 4 Biographies on Kuvempu, most number of Biographies on any Novelist.",
            "Snake Shyam of Mysore is the only Indian to be featured on Croc Chronicles by National Geographic channel.",
            "Anil Kumble became the first Indian bowler and the third in the world to reach the milestone of 600 Test wickets.",
            "Rahul Dravid holds a unique record of never getting out for a Golden duck in his 286 Test innings.",
            "The foundation stone for the Townhall in bangalore was laid by the then Maharaja of Mysore, Krishna Rajendra Wodeyar, on March 6, 1933.",
            "The Golden Howdah (Chinnada Ambari) used in the Jamboo Savari during Dasara weighs 750 kgs and is bigger than interiors of family car.",
            "The Kannada flag, bi-coloured flag (Turmeric-Vermilion) is the unofficial flag of Karnataka; only Jammu and Kashmir is allowed to have a state flag.",
            "Pampa, Ranna and Ponna are called \"three gems of ancient Kannada literature.",
            "The Murdeshwara temple's gopuram which is 40 meters tall is the second tallest in India.",
            "The Kadambas dynasty was founded by Mayurasharma in 345 CE, the first Kannada king.",
            "Chavundaraya a military commander in Ganga Dynasty is credited for building Gomateshwara.",
            "Yaduraya was the founder of Wodeyar Dynasty",
            "Sala is the founder of Hoysala Dynasty.",
            "Belur was built by king Vishnuvardhana in commemoration of his victory over the Cholas at Talakad in 1117 CE.",
            "Belur was reffered as Velapuri during 12th Century.",
            "Kaidala is the birthplace of the sculptor Jakanacharya who is credited for Belur's artwork.",
            "Darpana Sundari or \"The lady with the mirror\" is considered a marvellous sculpting by archeologists for the 12th century timeline.",
    };
    int i =0;

    public String nextfact()
    {
        Random r = new Random();
        int Low = 0;
        int High = facts.length;
        int Result = r.nextInt(High-Low) + Low;
        //i++;
        //if(i>=facts.length)
        //{i=0;}
        return facts[Result];
    }

    public String prevfact()
    {
        Random r = new Random();
        int Low = 0;
        int High = facts.length;
        int Result = r.nextInt(High-Low) + Low;
        //i++;
        //if(i>=facts.length)
        //{i=0;}
        return facts[Result];
       // i--;
       // if(i<0)
        //{i=facts.length;}
        // facts[i];
    }
}
